exclude: ['README.md', 'preview.sh', 'Gemfile', 'Gemfile.lock']

# Used to generate the site
title: "WatEvoCast Official Site"
title_short: "WatEvoCast"
email: "watevocast@evo.company"
description: "WatEvoCast about EVO Development and Developers"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://podcast.evo.run" # the base hostname & protocol for your site
itunes_url: "https://podcasts.apple.com/ua/podcast/watevocast/id1496597100"
google_url: "https://podcasts.google.com/feed/aHR0cHM6Ly9wb2RjYXN0LmV2by5ydW4vZXBpc29kZXMucnNz"

# itunes_id creates a smart banner on Safari in iOS prompting
# visitors to subscribe
# Uncomment next line to enable
itunes_id: 1496597100 # The ID is after the last slash in itunes_url above minus the letters "id"
#twitter_username: yourtwitter
#twitter_podcastname: yourpodcasttwitter

# For the SEO tag
seo:
  name: "WatEvoCast"
  type: "Technical"
  about: "WatEvoCast about EVO Development and Developers"
  person: "Larin Selyukh"

# Used to generate the iTunes-compatible RSS feed
podcast:
  owner:
    name: EVO
    email: watevocast@evo.company
  explicit: "no"
  image: /img/logo.jpg
  keywords: "evo, python, highload, javascript"
  categories:
    - category: "Technology"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugins
plugins:
  - jekyll-seo-tag
